// EXCHANGE RATE
export const EXCHANGE_RATE_SET_CUSTOM = 'EXCHANGE_RATE_SET_CUSTOM';
export const EXCHANGE_RATE_RESET = 'EXCHANGE_RATE_RESET';

// TRANSACTIONS
export const TRANSACTIONS_ADD = 'TRANSACTIONS_ADD';
export const TRANSACTIONS_DELETE = 'TRANSACTIONS_DELETE';


// MODALS
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_CLOSE = 'MODAL_CLOSE';

